# 指定使用 Just the Docs 主题
remote_theme: just-the-docs/just-the-docs

# --- 基础网站设置 ---
# 您的网站标题，会显示在浏览器标签页和导航栏顶部
title: 我的文档网站
# 网站的简短描述，可能被搜索引擎使用
description: 一个使用 Just the Docs 主题搭建的文档网站。

# --- Just the Docs 特有配置 (可选，可后续根据文档添加) ---
# 启用网站内搜索 (默认是开启的)
# search_enabled: true
#
# 设置网站的颜色主题 (可选 'light' 或 'dark')
# color_scheme: light
#
# 配置页脚内容 (示例)
# footer_content: "版权所有 &copy; 2025 KafkaTao."

# 更多配置选项请参考 Just the Docs 官方文档：
# https://just-the-docs.github.io/just-the-docs/docs/configuration/
